version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - dbmongo:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
  doc-editor:
    container_name: doc-editor
    build: .
    restart: unless-stopped
    environment:
      MONGODB_URL: mongodb://mongo:27017/doc-editor
    ports:
      - "3000:3000"
      - "1234:1234"
    depends_on:
      - mongo


volumes:
  dbmongo:

networks:
  doc-editor:
    name: Doc-Editor
    driver: bridge