name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/doc-editor-hub:${{ steps.package-version.outputs.current-version}}
            ${{ secrets.DOCKERHUB_USERNAME }}/doc-editor-hub:latest
      - name: Deploy to Jelastic Cloud
        run: |
          ./deploy_to_jelastic.sh \
            --hoster-api-host ${{ secrets.JELASTIC_HOST }} \
            --env-name ${{ secrets.JELASTIC_ENV_NAME }} \
            --session ${{ secrets.JELASTIC_SESSION }} \
            --tag ${{ steps.package-version.outputs.current-version }} \
            --node-id ${{ secrets.JELASTIC_NODE_ID }} \
            --use-existing-volumes true